#- name: Add APT repository
#  apt_repository:
#    validate_certs: no
#    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#    state: present
#  tags: install

- name: copy mongo
  copy:
    src: files/mongodb-org-mongos_3.2.10_amd64.deb
    dest: /tmp/mongodb-org-mongos_3.2.10_amd64.deb
  tags: install

- name: install mongo
  shell: sudo apt install /tmp/mongodb-org-mongos_3.2.10_amd64.deb
  tags: install

#- name: Install mongodb package 2
#  apt:
#    deb: /tmp/mongodb-org-mongos_3.2.10_amd64.deb
#    name: mongodb-org
#    state: present
#    allow_unauthenticated: yes
#    update_cache: yes
#  tags: install
#  ignore_errors: True

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install